language: bash
services: docker
before_install:
  - echo "We are in the docker folder!"
script:
  - docker-compose -build
before_deploy:
  - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
deploy:
  provider: script
  script:
    docker push gabrielrps/rest-with-spring-boot;
    docker push mysql-gabrielrps/rest-with-spring-boot;
  on:
    branch: master
notifications:
   email:false
